project_name: rode-collector-image-scanner
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
dockers:
  - image_templates:
      - "ghcr.io/rode/collector-image-scanner:latest"
      - "ghcr.io/rode/collector-image-scanner:{{ .Tag }}"
      - "ghcr.io/rode/collector-image-scanner:v{{ .Major }}"
      - "ghcr.io/rode/collector-image-scanner:v{{ .Major }}.{{ .Minor }}"
    extra_files:
      - "go.mod"
      - "go.sum"
      - "main.go"
      - "config"
      - "server"
      - "proto"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
